name: Objective Goal
about: Detailed description on what should happen to consider this a success.

links:
  - name: Links here
    url: /thelink

checklist:
  - name: Individual item that should happen (R:)
    status: unchecked
  - name: Individual item that should happen (R:)
    status: unchecked
  - name: Individual item that should happen (R:)
    status: unchecked
  - name: Individual item that should happen (R:)
    status: unchecked

related:
  - name: Reference meta issues and past issues
    url: #
